# Generated by Django 5.2.4 on 2025-07-15 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_notes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='notes',
            name='public',
            field=models.BooleanField(default=False),
        ),
    ]
